baseURL = "https://it.topli.ch"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "de"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The browser tab name
title = "Vitalii Stepchuk - IT-Systemingenieur & Cloud-Spezialist"

# In order to add version information in the page's footer set to true.
# enableGitInfo = true

# enable emoji processing in Markdown (valid only for pure markdown content)
enableEmoji = true

# Theme-specific variables `.Site.Params.myParamName`
[params]

    author = "Vitalii Stepchuk"
    keywords = ["IT Services", "System Engineer", "Cloud", "Backup", "Proxmox", "VEEAM", "KMU Support"]

    # blue, green, grey, violet or orange
    theme = "new"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/cover-image.png"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Vitalii Stepchuk"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Professionelle IT-Dienstleistungen für Privatkunden und KMU: Netzwerke, Virtualisierung, Backup, Cloud und Sicherheit."

    # Show a menu of languages available
    language_menu = true

    # Show also a language menu item for the current language, if false only
    # show the remaining languages
    show_current_lang = true

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Vitalii Stepchuk"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = false

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false

    # Options used for automatic image generation. see: https://gohugo.io/content-management/image-processing/
    image_options = "webp q90 lanczos photo"

    # Use "page_title | site_title" for <title> tags
    # e.g. <title>Legal | Jane Doe - Nutrition Coach & Chef Consultant</title>
    combine_page_and_site_title = false

    [params.footer]
    # Show contact icons for email/phone (if specified) in the footer of the page
    showContactIcons = false

    # Show links indicated with footer_menu and footer_menu_title in the footer of the page
    showFooterLinks = true

    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"

    [[params.contacts]]
        label = "phone"
        value = "+41 79 615 42 18"
        url = "tel:+41796154218"
        icon = "fa fa-phone"

    [[params.contacts]]
        label = "email"
        value = "v.stepchuk@topli.ch"
        url = "mailto:v.stepchuk@topli.ch"
        icon = "fa fa-envelope"

    #[[params.contacts]]
    #    label = "GitHub"
    #    value = "github.com/zjedi/hugo-scroll"
    #    url = "https://github.com/zjedi/hugo-scroll"
    #    icon = "fa-brands fa-github"

    # Add additional contacts here!
    # [[params.contacts]]
    #     label = ""
    #     value = ""
    #     url = ""
    #     icon = ""

# Define additional languages
[languages]
  [languages.de]
    weight = 10
    contentDir = "content/de"
    languageName = "Deutsch"

  [languages.en]
    weight = 20
    languageName = "English"
    contentDir = "content/en"
